cotizaciones/urls.py
from django.conf.urls import url

from .views import (
    AddItem,
    AddItemOtro,
    AddItemCantidad,
    CotizacionesListView,
    CambiarDiaEntregaView,
    TareaListView,
    RemisionListView,
    CotizacionEmailView,
    CotizadorView,
    EditarCotizacion,
    CambiarPorcentajeDescuentoView,
    CotizacionView,
    AddImagenCotizacionView,
    EliminarImagenCotizacionView,
    CambiarCantidadVentaPerdidaView
)

urlpatterns = [
    url(r'^add/(?P<item_id>[0-9]+)/(?P<precio>[0-9]+)/(?P<forma_pago>[0-9]+)/(?P<cot_id>[0-9]+)/(?P<tipo>[0-9]+)/(?P<tras_tipo>[\w\-]+)$',
        AddItem.as_view(), name='add_item_cotizacion'),
    url(r'^add_qty/$', AddItemCantidad.as_view(), name='add_qty_item_cotizacion'),
    url(r'^cambiar_dias/$', CambiarDiaEntregaView.as_view(), name='cambiar_dias_item_cotizacion'),
    url(r'^cambiar_descuento/$', CambiarPorcentajeDescuentoView.as_view(), name='cambiar_descuento_item_cotizacion'),
    url(r'^cambiar_venta_perdida/$', CambiarCantidadVentaPerdidaView.as_view(), name='cambiar_venta_perdida_item_cotizacion'),
    url(r'^detalle/(?P<pk>[0-9]+)$', CotizacionView.as_view(), name='detalle_cotizacion'),
    url(r'^enviar/$', CotizacionEmailView.as_view(), name='enviar'),
    url(r'^list/$', CotizacionesListView.as_view(), name='listar_cotizaciones'),
    url(r'^list/(?P<tipo>[0-3]+)$', CotizacionesListView.as_view(), name='listar_cotizaciones'),
    url(r'^tareas/list/$', TareaListView.as_view(), name='listar_tareas'),
    url(r'^remisiones/list/$', RemisionListView.as_view(), name='listar_remisiones'),
    url(r'^buscar/$', CotizacionesListView.as_view(), name='buscar_cotizacion'),
    url(r'^editar_cotizacion/', EditarCotizacion.as_view(), name='editar_cotizacion'),
    url(r'^add_otro/', AddItemOtro.as_view(), name='add_item_otro_cotizacion'),
    url(r'^add_imagen_cotizacion/', AddImagenCotizacionView.as_view(), name='add_imagen_cotizacion'),
    url(r'^del_imagen_cotizacion/(?P<pk>[0-9]+)$', EliminarImagenCotizacionView.as_view(), name='del_imagen_cotizacion'),
    url(r'^cotizador/', CotizadorView.as_view(), name='cotizador'),

]

home/urls.py
from django.conf.urls import url

from .views import HomeView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home-index'),
]

odeco/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from trabajo_diario.views import TrabajoDiaView

urlpatterns = [
    url(r'^$', TrabajoDiaView.as_view(), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    # override the default urls
    url(r'^password/change/$',
        auth_views.password_change,
        name='password_change'),
    url(r'^password/change/done/$',
        auth_views.password_change_done,
        name='password_change_done'),
    url(r'^password/reset/$',
        auth_views.password_reset,
        name='password_reset'),
    url(r'^password/reset/done/$',
        auth_views.password_reset_done,
        name='password_reset_done'),
    url(r'^password/reset/complete/$',
        auth_views.password_reset_complete,
        name='password_reset_complete'),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.password_reset_confirm,
        name='password_reset_confirm'),
    url(r'^cotizaciones/', include('cotizaciones.urls', namespace="cotizaciones")),
    url(r'^bandas/', include('bandas.urls', namespace="bandas")),
    # url(r'^indicadores/', include('indicadores.urls', namespace="indicadores")),
    url(r'^reportes_ventas/', include('reportes_ventas.urls', namespace="reportes_ventas")),
    url(r'^trabajo_diario/', include('trabajo_diario.urls', namespace="trabajo_diario")),
    url(r'^despacho_mercancia/', include('despachos_mercancias.urls', namespace="despacho_mercancia")),
    url(r'^biable/', include('biable.urls', namespace="biable")),
    url(r'^geografia/', include('geografia_colombia.urls', namespace="geografia")),
    url(r'^contactos/', include('contactos.urls', namespace="contactos")),
    url(r'^seguimientos/', include('seguimientos.urls', namespace="seguimientos")),
]

if settings.DEBUG:
    # import debug_toolbar
    # urlpatterns += [
    #     url(r'^__debug__/', include(debug_toolbar.urls)),
    # ]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seguimientos/urls.py
from django.conf.urls import url

from .views import (
    UsuariosConSeguimientoGestionComercialListView,
    GestionComercialUsuarioList
)

urlpatterns = [
    url(r'^usuarios_gestion_comercial_lista/$', UsuariosConSeguimientoGestionComercialListView.as_view(),
        name='usuarios_gestion_comercial_list'),
    url(r'^gestion_comercial_usuario/(?P<pk>[0-9]+)$', GestionComercialUsuarioList.as_view(),
        name='usuarios_gestion_comercial'),
]

cotizaciones/models.py
import datetime
import random

from django.utils import timezone
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from imagekit.models import ImageSpecField
from pilkit.processors import ResizeToFill

from bandas.models import Banda
from model_utils.models import TimeStampedModel

from .managers import CotizacionesEstadosQuerySet
from productos.models import Producto, ArticuloCatalogo
from listasprecios.models import FormaPago
from biable.models import FacturasBiable, Cliente as ClienteBiable
from geografia_colombia.models import Ciudad
from contactos.models import ContactoEmpresa


# Create your models here.
# region Cotizaciones
class Cotizacion(TimeStampedModel):
    ESTADOS = (
        ('INI', 'Iniciado'),
        ('ENV', 'Enviada'),
        ('ELI', 'Rechazada'),
        ('REC', 'Recibida'),
        ('PRO', 'En Proceso'),
        ('FIN', 'Entragada Totalmente'),
    )
    estado = models.CharField(max_length=10, choices=ESTADOS, default='INI')
    nro_contacto = models.CharField(null=True, blank=True, max_length=30)  # validators should be a list
    email = models.EmailField(max_length=150)
    nombres_contacto = models.CharField(max_length=120)
    pais = models.CharField(max_length=120, blank=True, null=True)
    ciudad = models.CharField(max_length=120, blank=True, null=True)
    apellidos_contacto = models.CharField(max_length=120)
    razon_social = models.CharField(max_length=120, blank=True, null=True)
    nro_cotizacion = models.CharField(max_length=120)
    fecha_envio = models.DateTimeField(null=True, blank=True)
    total = models.DecimalField(max_digits=18, decimal_places=0, default=0)
    total_venta_perdida = models.DecimalField(max_digits=18, decimal_places=2, default=0)
    descuento = models.DecimalField(max_digits=18, decimal_places=2, default=0)
    usuario = models.ForeignKey(User, related_name='mis_cotizaciones')
    creado_por = models.ForeignKey(User, related_name='cotizaciones_creadas', editable=False)
    observaciones = models.TextField(max_length=300, blank=True, null=True)
    en_edicion = models.BooleanField(default=False)
    version = models.PositiveIntegerField(default=1)
    ciudad_despacho = models.ForeignKey(Ciudad, null=True, blank=True)
    cliente_biable = models.ForeignKey(ClienteBiable, null=True, blank=True, related_name='mis_cotizaciones')
    cliente_nuevo = models.BooleanField(default=False)
    otra_ciudad = models.BooleanField(default=False)
    sucursal_sub_empresa = models.CharField(max_length=120, blank=True, null=True, verbose_name='Empresa o Sucursal')
    actualmente_cotizador = models.BooleanField(default=False, editable=False)
    contacto = models.ForeignKey(ContactoEmpresa, null=True, blank=True, related_name='mis_cotizaciones')
    contacto_nuevo = models.BooleanField(default=False)

    estados = CotizacionesEstadosQuerySet.as_manager()
    objects = models.Manager()

    class Meta:
        permissions = (
            ('full_cotizacion', 'Full Cotizacion'),
            ('gestion_cotizaciones', 'Gestionar Cotizaciones'),
            # ('hacer_cotizacion', 'Hacer Cotización'),
        )

    def get_absolute_url(self):
        return reverse("cotizaciones:detalle_cotizacion", kwargs={"pk": self.pk})

    def update_total(self):
        "updating..."
        total = 0
        descuento = 0
        total_venta_perdida = 0
        items = self.items.all()
        for item in items:
            total += item.total
            descuento += item.descuento
            total_venta_perdida += item.valor_venta_perdida_total
        self.total = total
        self.total_venta_perdida = total_venta_perdida
        self.descuento = descuento
        self.save()

    def set_estado(self, estado):
        self.estado = estado
        self.save()

    def get_rentabilidad_actual_total(self):
        rentabilidad = 0
        for item in self.items.all():
            rentabilidad += item.get_rentabilidad_actual_total()
        return rentabilidad

    def __str__(self):
        return "%s" % self.nro_cotizacion


# endregion

# region ItemCotizacion
class ItemCotizacion(TimeStampedModel):
    cotizacion = models.ForeignKey(Cotizacion, related_name="items")
    item = models.ForeignKey(Producto, related_name="cotizaciones", null=True)
    banda = models.ForeignKey(Banda, related_name="cotizaciones", null=True)
    articulo_catalogo = models.ForeignKey(ArticuloCatalogo, related_name="cotizaciones", null=True)
    cantidad = models.DecimalField(max_digits=18, decimal_places=3, null=True)

    cantidad_venta_perdida = models.DecimalField(max_digits=18, decimal_places=2, default=0)
    motivo_venta_perdida = models.CharField(max_length=120, default="NA")
    transporte_tipo = models.CharField(max_length=120)
    cantidad_total = models.DecimalField(max_digits=18, decimal_places=2, default=0)
    valor_venta_perdida_total = models.DecimalField(max_digits=18, decimal_places=2, default=0)

    precio = models.DecimalField(max_digits=18, decimal_places=2)
    forma_pago = models.ForeignKey(FormaPago, related_name="items_cotizaciones", null=True)
    p_n_lista_descripcion = models.CharField(max_length=120, null=True, verbose_name='Descripción Otro')
    p_n_lista_referencia = models.CharField(max_length=120, null=True, verbose_name='Referencia Otro', blank=True)
    p_n_lista_unidad_medida = models.CharField(max_length=120, null=True, verbose_name='Unidad Medida')
    total = models.DecimalField(max_digits=18, decimal_places=2)
    dias_entrega = models.PositiveIntegerField(default=0)
    porcentaje_descuento = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    descuento = models.DecimalField(max_digits=18, decimal_places=2, default=0)

    def get_nombre_item(self):
        if self.item:
            nombre = self.item.descripcion_comercial
        elif self.articulo_catalogo:
            nombre = self.articulo_catalogo.nombre
        elif self.banda:
            nombre = self.banda.descripcion_comercial
        else:
            nombre = self.p_n_lista_descripcion
        return nombre

    def get_referencia_item(self):
        if self.item:
            nombre = self.item.referencia
        elif self.articulo_catalogo:
            nombre = self.articulo_catalogo.referencia
        elif self.banda:
            nombre = self.banda.referencia
        else:
            nombre = self.p_n_lista_referencia
        return nombre

    def get_unidad_item(self):
        if self.item:
            nombre = self.item.unidad_medida
        elif self.articulo_catalogo:
            nombre = self.articulo_catalogo.unidad_medida
        elif self.banda:
            nombre = "Metro"
        else:
            nombre = self.p_n_lista_unidad_medida
        return nombre

    def get_costo_cop_actual_unidad(self):
        if self.item:
            costo = self.item.get_costo_cop()
        elif self.articulo_catalogo:
            costo = self.articulo_catalogo.get_costo_cop()
        elif self.banda:
            costo = self.banda.get_costo_cop()
        else:
            costo = 0
        return round(costo, 0)

    def get_costo_cop_actual_total(self):
        return round(self.get_costo_cop_actual_unidad() * self.cantidad_total, 0)

    def get_rentabilidad_actual_total(self):
        costo = self.get_costo_cop_actual_total()
        return round(self.total - costo, 0)

    def get_margen_rentabilidad_actual(self):
        margen = 0
        if not self.p_n_lista_descripcion:
            if self.total != 0:
                return round((self.get_rentabilidad_actual_total() * 100) / self.total, 2)
        return margen

    def get_tiempo_entrega_prometido(self):
        if self.dias_entrega == 0:
            return "Inmediato"
        if self.dias_entrega == 1:
            return "%s dia" % self.dias_entrega
        return "%s dias" % self.dias_entrega


# endregion

# region Remisiones
class RemisionCotizacion(TimeStampedModel):
    tipo_remision = models.CharField(max_length=2, choices=(('RM', 'RM'), ('RY', 'RY')), default='RM')
    nro_remision = models.PositiveIntegerField()
    factura_biable = models.ForeignKey(FacturasBiable, null=True, blank=True, related_name='mis_remisiones')
    fecha_prometida_entrega = models.DateField()
    entregado = models.BooleanField(default=False)
    cotizacion = models.ForeignKey(Cotizacion, related_name="mis_remisiones")

    class Meta:
        verbose_name_plural = "Remisiones x Cotización"

    def __str__(self):
        return "%s" % self.nro_remision

    def get_dias_a_fecha_fin(self):
        return (self.fecha_prometida_entrega - datetime.date.today()).days


# endregion

# region Tareas
class TareaCotizacion(TimeStampedModel):
    nombre = models.CharField(max_length=120)
    descripcion = models.TextField(max_length=300)
    fecha_inicial = models.DateField()
    fecha_final = models.DateField()
    esta_finalizada = models.BooleanField(default=False)
    cotizacion = models.ForeignKey(Cotizacion, null=True, blank=True, related_name="mis_tareas")

    class Meta:
        verbose_name_plural = "Tareas"

    def __str__(self):
        return "%s" % self.nombre

    def get_dias_a_fecha_fin(self):
        return (self.fecha_final - datetime.date.today()).days


class ComentarioCotizacion(TimeStampedModel):
    comentario = models.TextField(max_length=300)
    usuario = models.ForeignKey(User, on_delete=models.PROTECT, related_name='comentarios_cotizaciones')
    cotizacion = models.ForeignKey(Cotizacion, null=True, blank=True, related_name="mis_comentarios")


def imagen_upload_to(instance, filename):
    fecha_hoy = timezone.now().strftime('%Y%m%d%H%M%S')
    split_filename = filename.split(".")
    file_extention = split_filename[-1]
    basename = split_filename[0]
    new_filename = '%s %s' % (basename, fecha_hoy)
    return "img/coti/%s/%s.%s" % (instance.cotizacion.id, new_filename, file_extention)


class ImagenCotizacion(TimeStampedModel):

seguimientos/views.py
from django.contrib.auth.models import User
from django.views.generic.list import ListView

from braces.views import LoginRequiredMixin

from .mixins import SeguimientoGestionComercialMixin
from .models import SeguimientoComercialCliente


# Create your views here.
class UsuariosConSeguimientoGestionComercialListView(LoginRequiredMixin, ListView):
    model = User
    context_object_name = 'lista_usuarios'
    template_name = 'seguimientos/gestion_comercial/usuarios_gestion_comercial_list.html'

    def get_queryset(self):
        qs = None
        if self.request.user.has_perm('biable.reporte_ventas_todos_vendedores'):
            qs = super().get_queryset()
            qs2 = SeguimientoComercialCliente.objects.values_list('creado_por').filter(
                creado_por__isnull=False).all().distinct()
            qs = qs.filter(id__in=qs2)[0:100]
        return qs


class GestionComercialUsuarioList(LoginRequiredMixin, SeguimientoGestionComercialMixin, ListView):
    model = SeguimientoComercialCliente
    template_name = 'seguimientos/gestion_comercial/usuarios_gestion_comercial_usuario.html'
    context_object_name = 'mi_gestion_comercial'

    def get_queryset(self):
        qs = None
        if self.request.user.has_perm('biable.reporte_ventas_todos_vendedores'):
            tipo = self.request.GET.get('tipo_seguimiento_comercial')
            qs = self.get_seguimiento_comercial(nro_registros=100, usuario_pk=self.kwargs.get('pk'), tipo=tipo)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['vendedor'] = User.objects.get(pk=self.kwargs.get('pk'))
        return context

templates/cotizaciones/cotizacion/cabecera.html
{% load crispy_forms_tags %}
{% if puede_modificar == True %}
    {% if not cotizacion.estado == 'FIN' and not cotizacion.estado == 'ELI' %}
        <form method="post" action="{% url 'cotizaciones:enviar' %}">
            {% csrf_token %}
            <input type="hidden" name="id" value="{{ cotizacion.id }}"/>
            <small>
                <button type="submit" name="enviar"><i class="fa fa-envelope" aria-hidden="true"></i> Reenviar Email
                </button>
            </small>
        </form>

        <form method="post" action="{% url 'cotizaciones:editar_cotizacion' %}">
            {% csrf_token %}
            {% if not cotizacion.en_edicion %}
                <p>
                    <small>
                        <button name="editar" value="{{ cotizacion.pk }}" type="submit"><i class="fa fa-pencil"
                                                                                           aria-hidden="true"></i>
                            Editar
                        </button>
                    </small>
                </p>
            {% endif %}
        </form>
    {% endif %}
{% endif %}
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
<div class="row">
    <div class="col-xs-12 col-sm-8 col-md-9">
        <div class="div_detalle">
            <h4>Fecha Envio:
                <small>{{ cotizacion.fecha_envio }}</small>
            </h4>
            <h4>Estado:
                <small>{{ cotizacion.get_estado_display }}</small>
            </h4>
            <h4>Nro Version:
                <small>{{ cotizacion.version }}</small>
            </h4>
            <h4>Vendedor:
                <small>{{ cotizacion.usuario.get_full_name }}</small>
            </h4>
            {% if puede_modificar == True %}
                {% crispy asignar_vendedor_form %}
            {% endif %}
        </div>
        <h2>Información Cliente</h2>
        <div class="row div_detalle">
            <div class="col-xs-12 col-sm-6">
                <h4>Razón Social:
                    <small>
                        {% if cotizacion.cliente_nuevo %}
                            {{ cotizacion.razon_social }}
                        {% else %}
                            <a href="{{ cotizacion.cliente_biable.get_absolute_url }}"
                               target="_blank">{{ cotizacion.cliente_biable.nombre }}</a>
                        {% endif %}
                    </small>
                </h4>
                <h4>Nombre:
                    <small>{{ cotizacion.nombres_contacto }} {{ cotizacion.apellidos_contacto }}</small>
                </h4>
                <h4>Correo Electrónico:
                    <small>{{ cotizacion.email }}</small>
                </h4>
            </div>
            <div class="col-xs-12 col-sm-6">
                <h4>Número de Contacto:
                    <small>{{ cotizacion.nro_contacto }}</small>
                </h4>
                <h4>Ubicación
                    <small>
                        {% if cotizacion.otra_ciudad %}
                            {{ cotizacion.pais }} - {{ cotizacion.ciudad }}
                        {% else %}
                            {{ cotizacion.ciudad_despacho.nombre }} -
                            {{ cotizacion.ciudad_despacho.departamento.nombre }} -
                            {{ cotizacion.ciudad_despacho.departamento.pais.nombre }}
                        {% endif %}
                    </small>
                </h4>
                {% if cotizacion.observaciones %}
                    <h4>Observación
                        <small>
                            {{ cotizacion.observaciones|safe }}
                        </small>
                    </h4>
                {% endif %}
            </div>
        </div>
    </div>
    {% if puede_modificar == True %}
        <div class="col-xs-12 col-sm-4 col-md-3">
            <form method="post">
                {% csrf_token %}
                {% if not cotizacion.estado == 'FIN' and not cotizacion.estado == 'ELI' %}
                    <input class="btn btn-primary" name="form_estado" value="Rechazar" type="submit"/>
                {% endif %}
                {% if cotizacion.estado == 'ENV' %}
                    <input class="btn btn-primary" name="form_estado" value="Recibida" type="submit"/>
                {% endif %}
                {% if cotizacion.estado == 'REC' %}
                    <input class="btn btn-primary" name="form_estado" value="Aceptada" type="submit"/>
                {% endif %}
                {% if cotizacion.estado == 'PRO' %}
                    <input class="btn btn-primary" name="form_estado" value="Completada" type="submit"/>
                {% endif %}
            </form>
        </div>
    {% endif %}
</div>

templates/cotizaciones/cotizacion/comentarios.html
{% with comentarios_list=cotizacion.mis_comentarios.all %}
    {% if comentarios_list %}
        <div class="col-xs-12">
            <div class="page-header">
                <h1>
                    Comentarios<span class="badge">{{ cotizacion.mis_comentarios.count }}</span>
                </h1>
            </div>

            {% for comentario in comentarios_list %}
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <strong>{{ comentario.usuario.get_full_name }}</strong> <span
                            class="text-muted">{{ comentario.created|timesince }}</span>
                    </div>
                    <div class="panel-body">
                        {{ comentario.comentario }}
                    </div><!-- /panel-body -->
                </div><!-- /panel panel-default -->
            {% endfor %}

        </div>
    {% endif %}
{% endwith %}

templates/cotizaciones/cotizacion/cotizacion_detalle.html
{% extends 'cotizaciones/base_cotizacion.html' %}
{% load crispy_forms_tags %}
{% block titulo_pagina %}
    Cotizacion {{ cotizacion.nro_cotizacion }}
    {% if not cotizacion.estado == 'FIN' and not cotizacion.estado == 'ELI' %}
        {% if cotizacion.en_edicion %}
            <small> En Edicion</small>
        {% endif %}
    {% endif %}
{% endblock %}

{% block content_page %}
    {% include 'cotizaciones/cotizacion/cabecera.html' %}
    {% include 'cotizaciones/cotizacion/detalle.html' %}
    {% include 'cotizaciones/cotizacion/imagenes.html' %}
    {% include 'cotizaciones/cotizacion/seguimientos.html' %}
    {% include 'cotizaciones/cotizacion/comentarios.html' %}
    {% include 'cotizaciones/cotizacion/remisiones.html' %}
    {% if puede_modificar == True %}
        {% crispy comentario_form %}
        <div class="row">
            {% if cotizacion.estado == 'PRO' %}
                <div class="col-md-6">
                    <h2>Remisiones</h2>
                    <hr/>
                    {% crispy remisiones helper_remision %}
                </div>
            {% endif %}

            {% if cotizacion.estado == 'PRO' or cotizacion.estado == 'ENV' or cotizacion.estado == 'REC' %}
                <div class="col-md-6">
                    <h2>Tareas</h2>
                    <hr/>
                    {% crispy tareas helper_tarea %}
                </div>
            {% endif %}
        </div>
    {% endif %}
{% endblock %}

templates/cotizaciones/cotizacion/detalle.html
<table class="table table-bordered table-striped">
    <thead>
    <tr>
        <th>
            Rentable
        </th>
        <th>
            Referencia
        </th>
        <th>
            Nombre
        </th>
        <th style="background: beige; color: black">
            Cant. Ini
        </th>
        <th style="background: beige; color: black">
            Cant. Vent. P
        </th>
        <th style="background: beige; color: black">
            Valor. Vent. P
        </th>
        <th style="background: beige; color: black">
            Motivo Vent. P
        </th>
        <th>
            Cant. Total
        </th>
        <th>
            Uni. Emp
        </th>
        <th>
            Pre. Uni.
        </th>
        <th>
            Descuento
        </th>
        <th>
            Total
        </th>
        <th>
            Forma de Pago
        </th>
        {% if perms.cotizaciones.full_cotizacion %}
            <th>
                Costo Base
            </th>
            <th>
                Costo Total
            </th>
            <th>
                Rent.
            </th>
            <th>
                Mrg Rent.
            </th>
        {% endif %}
        <th>
            Tiem. Entrega
        </th>
    </tr>
    </thead>
    <tbody>
    {% for item in cotizacion.items.all %}
        <tr>
            <td>
                {% if item.get_margen_rentabilidad_actual < 0 %}
                    <i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
                {% else %}
                    <i class="fa fa-check-circle" aria-hidden="true"></i>
                {% endif %}
            </td>
            <td>
                {{ item.get_referencia_item }}
            </td>
            <td>
                {{ item.get_nombre_item }}
            </td>
            <td>
                {{ item.cantidad|floatformat:2 }}
            </td>
            <td>
                {{ item.cantidad_venta_perdida|floatformat:2 }}
            </td>
            <td>
                {{ item.valor_venta_perdida_total|floatformat:2 }}
            </td>
            <td>
                {{ item.motivo_venta_perdida }}
            </td>
            <td>
                {{ item.cantidad_total|floatformat:2 }}
            </td>
            <td>
                {{ item.get_unidad_item }}
            </td>
            <td>
                {{ item.precio }}
            </td>
            <td>
                {{ item.descuento }}
            </td>
            <td>
                {{ item.total }}
            </td>
            <td>
                {{ item.forma_pago }}
            </td>
            {% if perms.cotizaciones.full_cotizacion %}
                <td>
                    {{ item.get_costo_cop_actual_unidad }}
                </td>
                <td>
                    {{ item.get_costo_cop_actual_total }}
                </td>
                <td>
                    {{ item.get_rentabilidad_actual_total }}
                </td>
                <td>
                    {{ item.get_margen_rentabilidad_actual }} %
                </td>
            {% endif %}
            <th>
                {{ item.get_tiempo_entrega_prometido }}
            </th>
        </tr>
    {% endfor %}
    </tbody>
    <tfoot>
    <tr>
        <td class="clear"></td>
        <td colspan="4"> Total Venta Perdida:</td>
        <td> {{ cotizacion.total_venta_perdida }} </td>
    </tr>
    <tr>
        <td class="clear"></td>
        <td colspan="9"> Descuento:</td>
        <td> {{ cotizacion.descuento }} </td>
    </tr>
    <tr>
        <td class="clear"></td>
        <td colspan="10"> Total:</td>
        <td> {{ cotizacion.total }} </td>
    </tr>
    </tfoot>
</table>

templates/cotizaciones/cotizacion/imagenes.html
{% with imagenes=cotizacion.mis_imagenes.all %}
    {% if imagenes %}
        <h3>Imagenes Adjuntas</h3>
        <div class="panel panel-default" style="padding: 1rem">
            {% for imagen in imagenes %}
                <a href="{{ imagen.imagen.url }}" target="_blank">
                    <img src="{{ imagen.imagen_cotizador.url }}"/>
                </a>
            {% endfor %}
        </div>
    {% endif %}
{% endwith %}

templates/cotizaciones/cotizacion/seguimientos.html
{% with seguimientos=cotizacion.tarea_diaria_cotizacion.seguimientos.all %}
    {% if seguimientos %}
        <h2>Seguimientos</h2>
        <ul>
            {% for seguimiento in seguimientos %}
                <li>
                    <i class="fa fa-comments" aria-hidden="true"></i> {{ seguimiento.observacion }}
                    -
                    <small> {{ seguimiento.created }}</small>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
{% endwith %}