despachos_mercancias/urls.py
from django.conf.urls import url

from .views import (
    EnvioTransportadoraTCCUpdateView,
    EnvioTransportadoraTCCDetailView,
    EnvioTransportadoraTCCReporteView
)

urlpatterns = [
    url(r'envio_update/(?P<pk>[0-9]+)/$', EnvioTransportadoraTCCUpdateView.as_view(), name='envio-update'),
    url(r'envio_detail/(?P<pk>[0-9]+)/$', EnvioTransportadoraTCCDetailView.as_view(), name='envio-detail'),
    url(r'reporte_seguimiento/$', EnvioTransportadoraTCCReporteView.as_view(), name='envio-reporte'),
]

home/urls.py
from django.conf.urls import url

from .views import HomeView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home-index'),
]

despachos_mercancias/models.py
from django.db import models
from django.db.models import Q
from django.urls import reverse
from django.utils import timezone

from model_utils.models import TimeStampedModel

from biable.models import Cliente, FacturasBiable
from geografia_colombia.models import Ciudad


# Create your models here.
class EnvioTransportadoraTCCQuerySet(models.QuerySet):
    def con_boom(self):
        return self.filter(
            ~Q(nro_tracking_boom__exact='')
            &
            Q(fecha_entrega_boom__isnull=True)
        )

    def con_entrega(self):
        return self.filter(
            Q(fecha_entrega__isnull=True)
        )


class EnvioTransportadoraTCCPendientesManager(models.Manager):
    def get_queryset(self):
        return EnvioTransportadoraTCCQuerySet(self.model, using=self._db).filter(
            (
                ~Q(nro_tracking_boom__exact='') &
                Q(fecha_entrega_boom__isnull=True)
            )
            |
            Q(fecha_entrega__isnull=True)
        )

    def boom(self):
        qs1 = self.get_queryset().con_boom()
        qs2 = self.get_queryset().con_entrega()
        qsF = qs1.exclude(pk__in=qs2)
        return qsF

    def entrega(self):
        qs1 = self.get_queryset().con_boom()
        qs2 = self.get_queryset().con_entrega()
        qsF = qs2.exclude(pk__in=qs1)
        return qsF

    def entrega_boom(self):
        qs1 = self.get_queryset().con_boom()
        qs2 = self.get_queryset().con_entrega()
        qsF = self.get_queryset().filter(
            Q(pk__in=qs1) &
            Q(pk__in=qs2)
        ).distinct()
        return qsF


class EnvioTransportadoraTCC(TimeStampedModel):
    TIPO_ENVIO = (
        ('PQ', 'Paquetería'),
        ('MS', 'Mensajería')
    )
    ESTADO_ENTREGA = (
        ('CP', 'Cumplido parcial del despacho por presentar novedad'),
        ('DD', 'Descargado en Destino'),
        ('PE', 'En proceso de entrega'),
        ('RP', 'En Reparto'),
        ('EN', 'Entregada'),
        ('ER', 'Entregada (Retorno Odeco)'),
        ('NS', 'Novedad Solucionada'),
        ('RO', 'Recibido en Origen'),
        ('NA', 'NO FUE ENVIADA')
    )
    FORMA_PAGO = (
        ('NOR', 'NORMAL'),
        ('CTA', 'CUENTA'),
        ('RD', 'RD'),
        ('FCE', 'FCE'),
        ('NA', 'NO VIAJA'),
        ('9AM', '9AM'),
    )

    fecha_envio = models.DateField()
    fecha_entrega = models.DateField(null=True, blank=True)
    nro_factura_transportadora = models.PositiveIntegerField(null=True, blank=True)
    nro_tracking = models.CharField(max_length=60)
    cliente = models.ForeignKey(Cliente, null=True, blank=True, related_name='mis_despachos')
    cliente_alternativo = models.CharField(max_length=60, null=True, blank=True)
    tipo = models.CharField(max_length=2, choices=TIPO_ENVIO, default='PQ')
    nro_tracking_boom = models.CharField(max_length=60, blank=True, null=True)
    fecha_entrega_boom = models.DateField(null=True, blank=True)
    forma_pago = models.CharField(max_length=3, choices=FORMA_PAGO)
    observacion = models.TextField(max_length=200, blank=True, null=True)
    estado = models.CharField(max_length=2, choices=ESTADO_ENTREGA)
    valor = models.DecimalField(decimal_places=2, max_digits=18, null=True, blank=True)
    valor_boom = models.DecimalField(decimal_places=2, max_digits=18, null=True, blank=True)
    facturas = models.ManyToManyField(FacturasBiable, related_name='envios', blank=True, verbose_name='Facturas')
    ciudad = models.ForeignKey(Ciudad, related_name='mis_envios_tcc', on_delete=models.PROTECT)

    objects = models.Manager()
    pendientes = EnvioTransportadoraTCCPendientesManager()

    class Meta:
        permissions = (
            ('ver_segui_envio_tcc', 'Seg. Envios TCC'),
        )

    def get_numero_dias_entrega(self):
        if self.fecha_entrega:
            dias = (abs((self.fecha_entrega - self.fecha_envio).days))
            if dias > 1:
                return "%s días" % (dias)
            else:
                return "%s día" % (dias)
        return "Sin Entregar"

    def get_numero_dias_desde_envio(self):
        fecha_actual = timezone.now().date()
        if not self.fecha_entrega:
            dias = (abs((fecha_actual - self.fecha_envio).days))
            if dias > 1:
                return "%s días" % (dias)
            else:
                return "%s día" % (dias)
        return "Entregada"

    def get_numero_dias_entrega_boom(self):
        if self.nro_tracking_boom:
            if self.fecha_entrega_boom:
                dias = (abs((self.fecha_entrega_boom - self.fecha_envio).days))
                if dias > 1:
                    return "%s días" % (dias)
                else:
                    return "%s día" % (dias)
            return "Sin Entregar"
        return ""

    def get_numero_dias_desde_envio_boom(self):
        if self.nro_tracking_boom:
            fecha_actual = timezone.now().date()
            if not self.fecha_entrega_boom:
                dias = (abs((fecha_actual - self.fecha_envio).days))
                if dias > 1:
                    return "%s días" % (dias)
                else:
                    return "%s día" % (dias)
            return "Entregada"
        return ""

    def get_absolute_update_url(self):
        return reverse("despacho_mercancia:envio-update", kwargs={"pk": self.pk})

    def get_absolute_url(self):
        return reverse("despacho_mercancia:envio-detail", kwargs={"pk": self.pk})

despachos_mercancias/forms.py
from crispy_forms.bootstrap import StrictButton, PrependedText, FormActions, FieldWithButtons
from crispy_forms.layout import Submit, Layout, Div, Field, Button, HTML
from django import forms
from django.forms import ModelForm

from crispy_forms.helper import FormHelper
from django.urls import reverse

from .models import EnvioTransportadoraTCC


class EnvioTccForm(ModelForm):
    fecha_entrega = forms.DateField(
        widget=forms.TextInput(
            attrs={'type': 'date'}
        ), required=False
    )
    fecha_entrega_boom = forms.DateField(
        widget=forms.TextInput(
            attrs={'type': 'date'}
        ), required=False
    )

    class Meta:
        model = EnvioTransportadoraTCC
        fields = ('fecha_entrega', 'fecha_entrega_boom', 'estado', 'observacion')

    def __init__(self, *args, **kwargs):
        super(EnvioTccForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'id-envioTccForm'
        self.helper.form_method = "post"

        self.helper.form_class = 'form-inline'
        self.helper.layout = Layout(
            HTML('<h2>Seguimiento</h2>'),
            Div(
                Field('fecha_entrega'),
                Field('estado'),
            ),
        )

        boom = Div(
            HTML('<h2>Seguimiento Boom</h2>'),
            Div(
                Field('fecha_entrega_boom'),
            )
        )
        if not self.instance.nro_tracking_boom:
            boom = Div(
                Div(
                    Field('fecha_entrega_boom'),
                ), style="display:none"
            )

        observacion = Div(
            HTML('<h2>Observaciones</h2>'),
            Div(
                Field('observacion')
            ),
            FormActions(
                Submit('guardar', 'Guardar')
            )
        )

        self.helper.layout.fields.append(boom)

        self.helper.layout.fields.append(observacion)

        self.helper.all().wrap(Field, css_class="form-control")

despachos_mercancias/views.py
from django.views.generic import TemplateView
from django.views.generic.edit import UpdateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from braces.views import SelectRelatedMixin, PrefetchRelatedMixin, LoginRequiredMixin

from .models import EnvioTransportadoraTCC
from .forms import EnvioTccForm


# Create your views here.

class EnvioTransportadoraTCCUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'despachos_mercancias/envio_tcc_update.html'
    model = EnvioTransportadoraTCC
    form_class = EnvioTccForm


class EnvioTransportadoraTCCDetailView(LoginRequiredMixin, PrefetchRelatedMixin, SelectRelatedMixin, DetailView):
    template_name = 'despachos_mercancias/envio_tcc_detail.html'
    model = EnvioTransportadoraTCC
    select_related = ["ciudad", "ciudad__departamento", "cliente"]
    prefetch_related = ["facturas", "facturas__cliente", "facturas__vendedor"]


class EnvioTransportadoraTCCReporteView(LoginRequiredMixin, SelectRelatedMixin, TemplateView):
    template_name = 'despachos_mercancias/reporte_seguimiento.html'
    select_related = ["ciudad", "ciudad__departamento", "cliente"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        qs = EnvioTransportadoraTCC.pendientes
        context["boom"] = qs.boom().select_related("ciudad", "ciudad__departamento", "cliente")
        context["entrega"] = qs.entrega().select_related("ciudad", "ciudad__departamento", "cliente")
        context["entrega_boom"] = qs.entrega_boom().select_related("ciudad", "ciudad__departamento", "cliente")
        return context

templates/despachos_mercancias/envio_tcc_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Detalles Envío TCC
        {% if not object.fecha_entrega %}
            <small><a href="{{ object.get_absolute_update_url }}"> Editar </a></small>
        {% elif not object.fecha_entrega_boom and object.nro_tracking_boom %}
            <small><a href="{{ object.get_absolute_update_url }}"> Editar </a></small>
        {% endif %}
    </h1>
    <div class="row">
        <div class="col-md-6">
            <h3>Información General</h3>
            <hr>
            <p>
                <span class="label">Cliente:</span>
                {% if object.cliente %}{{ object.cliente }} {% else %} {{ object.cliente_alternativo }} {% endif %}
            </p>
            <p>
                <span class="label">Departamento:</span> {{ object.ciudad.departamento.nombre }}
            </p>
            <p>
                <span class="label">Ciudad:</span> {{ object.ciudad.nombre }}
            </p>
            <p>
                <span class="label">Estado:</span> {{ object.get_estado_display }}
            </p>

            {% if object.nro_factura_transportadora %}
                <p>
                    <span class="label">Nro Factura TCC:</span> {{ object.nro_factura_transportadora }}
                </p>
            {% endif %}

            <p>
                <span class="label">Fecha de Envío:</span> {{ object.fecha_envio }}
            </p>
            <p>
                <span class="label">Tipo Envío:</span> {{ object.get_tipo_display }}
            </p>
            <p>
                <span class="label">Forma de Pago:</span> {{ object.get_forma_pago_display }}
            </p>
            <p>
                <span class="label">Valor:</span> {{ object.valor }}
            </p>
        </div>
        <div class="col-md-6">
            <h3>Seguimiento Entrega</h3>
            <hr>
            <p>
                <span class="label">Nro de seguimiento:</span> {{ object.nro_tracking }}
            </p>
            {% if object.fecha_entrega %}
                <p>
                    <span class="label">Fecha de Entrega:</span> {{ object.fecha_entrega }}
                </p>
            {% endif %}
            {% if not object.fecha_entrega %}
                <p>
                    <span class="label">Días en Transito:</span>{{ object.get_numero_dias_desde_envio }}
                </p>
            {% else %}
                <p>
                    <span class="label">Día que se tomó la entrega:</span>{{ object.get_numero_dias_entrega }}
                </p>
            {% endif %}
            {% if object.nro_tracking_boom %}
                <h3>Servicio Boom</h3>
                <hr>
                <p>
                    <span class="label">Nro de Seguimiento Boom:</span> {{ object.nro_tracking_boom }}
                </p>
                <p>
                    <span class="label">Valor Boom:</span> {{ object.valor_boom }}
                </p>
                {% if object.fecha_entrega_boom %}
                    <p>
                        <span class="label">Fecha Entrega Boom:</span> {{ object.fecha_entrega_boom }}
                    </p>
                {% endif %}
            {% endif %}
        </div>
    </div>

    {% if object.observacion %}
        <p>
            <span class="label">Observación:</span> {{ object.observacion }}
        </p>
    {% endif %}
    {% if object.facturas.all %}
        <h2>Documentos Relacionados</h2>
        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>
                    Nro Factura
                </th>
                <th>
                    Vendedor
                </th>
                <th>
                    Cliente
                </th>
            </tr>

            </thead>
            <tbody>
            {% for factura in object.facturas.all %}
                <tr>
                    <td>
                        <a href="{{ factura.get_absolute_url }}">
                            {{ factura.tipo_documento }}-{{ factura.nro_documento }}
                        </a>
                    </td>
                    <td>
                        {{ factura.vendedor }}
                    </td>
                    <td>
                        {{ factura.cliente }}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    {% endif %}
{% endblock %}

templates/despachos_mercancias/envio_tcc_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    {% if not object.fecha_entrega %}
        <h1>Editar Envío TCC</h1>
        {% crispy form %}
    {% elif not object.fecha_entrega_boom and object.nro_tracking_boom %}
        <h1>Editar Envío TCC</h1>
        {% crispy form %}
    {% else %}
        Despacho esta cerrado, comunicarse con el administrador de despachos TCC para cualquier cambio
    {% endif %}
{% endblock %}

templates/despachos_mercancias/reporte_seguimiento.html
{% extends 'base.html' %}
{% block title %}
    Reporte de Seguimiento Envios TCC
{% endblock %}
{% block content %}
    <h1>Reporte de Seguimiento Envios TCC</h1>
    {% if perms.despachos_mercancias.ver_segui_envio_tcc %}
        {% if boom %}
            {% include 'despachos_mercancias/components/enviosTCC_table.html' with lista_envio=boom titulo="Envío Solo Boom" %}
        {% endif %}
        {% if entrega_boom %}
            {% include 'despachos_mercancias/components/enviosTCC_table.html' with lista_envio=entrega_boom titulo="Envío Boom y Entrega" %}
        {% endif %}
        {% if entrega %}
            {% include 'despachos_mercancias/components/enviosTCC_table.html' with lista_envio=entrega titulo="Envío Solo Entrega" %}
        {% endif %}
    {% else %}
        No tiene permisos suficientes para ver este informe
    {% endif %}
{% endblock %}